# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron's blog
tagline:          Coffee, Pastries, and code
url:              http://aahill.github.io
paginate:         1
baseurl:          /
author:
  name:           Aaron Hill
  url:            No twitter yet!
  email:          aahill017@live.com
  
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/aahill/aahill.io.github
