# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron's blog
tagline:          Coffee, Pastries, and code
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Aaron Hill
  url:            No twitter yet!
  email:          aahill@vassar.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
